spring:
  application:
    name: stark-security
  datasource:
    url: jdbc:h2:mem:starkdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: ${MAIL_USERNAME:mllangon@myuax.com}
    password: ${MAIL_PASSWORD:tu-contraseña}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,threaddump
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.stark: DEBUG

app:
  alerts:
    email-to: ${MAIL_TO:tu-email@gmail.com}
    email-from: ${MAIL_FROM:tu-email@gmail.com}
    email:
      html-enabled: true
    sms:
      enabled: true
      phone-numbers: "+346252551339"
    push:
      enabled: true
      device-tokens: "device_token_1,device_token_2,device_token_3"
  sensors:
    motion:
      off-hours:
        start: "20:00"
        end: "06:00"
    temperature:
      warn-threshold: 40
      critical-high: 50
      critical-low: 0

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:stark}
    username: ${DB_USER:stark}
    password: ${DB_PASSWORD:stark}
  jpa:
    hibernate:
      ddl-auto: validate

management:
  endpoint:
    health:
      show-details: never

server:
  forward-headers-strategy: native



